# Generated by Django 2.2.7 on 2019-12-02 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.IntegerField(choices=[('Python-built-in', 'Python Built-in Module'), ('Python-tool', 'Python Coding Tool'), ('Django', 'Django Tutorial'), ('Python', 'Python Tutorial'), ('Python-external', 'Python External Module'), ('Flask', 'Flask Tutorial')]),
        ),
    ]
