# Generated by Django 2.2.7 on 2019-12-04 09:52

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('myapp', '0002_auto_20191202_0737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='category',
        ),
        migrations.AddField(
            model_name='blog',
            name='Category',
            field=models.CharField(choices=[('Django', 'Django Tutorial'), ('Python-tool', 'Python Coding Tool'), ('Python-external', 'Python External Module'), ('Python-built-in', 'Python Built-in Module'), ('Python', 'Python Tutorial'), ('Flask', 'Flask Tutorial')], default='Python Tutorial', max_length=20),
        ),
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0),
        ),
    ]
