# Generated by Django 2.2.7 on 2019-12-05 07:21

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20191205_0719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Category',
            field=models.CharField(choices=[('Python-built-in', 'Python Built-in Module'), ('Python-external', 'Python External Module'), ('Python', 'Python Tutorial'), ('Python-tool', 'Python Coding Tool'), ('Flask', 'Flask Tutorial'), ('Django', 'Django Tutorial')], default='Python Tutorial', max_length=20),
        ),
        migrations.AlterField(
            model_name='headerad',
            name='Header_Ad',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
