# Generated by Django 2.2.7 on 2019-12-05 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20191205_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Category',
            field=models.CharField(choices=[('Django', 'Django Tutorial'), ('Python-built-in', 'Python Built-in Module'), ('Python', 'Python Tutorial'), ('Flask', 'Flask Tutorial'), ('Python-tool', 'Python Coding Tool'), ('Python-external', 'Python External Module')], default='Python Tutorial', max_length=20),
        ),
    ]
