# Generated by Django 2.2.7 on 2020-01-06 09:36

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20191205_0738'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Header_Ad', ckeditor.fields.RichTextField()),
                ('sidebar_one', ckeditor.fields.RichTextField()),
                ('sidebar_two', ckeditor.fields.RichTextField()),
                ('bottom', ckeditor.fields.RichTextField()),
                ('article_one', ckeditor.fields.RichTextField()),
                ('article_two', ckeditor.fields.RichTextField()),
                ('article_three', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='Category',
            field=models.CharField(choices=[('Python-tool', 'Python Coding Tool'), ('Python-built-in', 'Python Built-in Module'), ('Python-external', 'Python External Module'), ('Django', 'Django Tutorial'), ('Python', 'Python Tutorial'), ('Flask', 'Flask Tutorial')], default='Python Tutorial', max_length=20),
        ),
    ]
