# Generated by Django 2.2.7 on 2020-01-06 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20200106_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Category',
            field=models.CharField(choices=[('Python', 'Python Tutorial'), ('Django', 'Django Tutorial'), ('Flask', 'Flask Tutorial'), ('Python-built-in', 'Python Built-in Module'), ('Python-external', 'Python External Module'), ('Python-tool', 'Python Coding Tool')], default='Python Tutorial', max_length=20),
        ),
    ]
