# Generated by Django 2.2.7 on 2020-01-08 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20200106_1012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.FileField(upload_to='logos', verbose_name='Website Logo')),
                ('siteicon', models.FileField(upload_to='icons', verbose_name='Website Icon')),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='Category',
            field=models.CharField(choices=[('Python-built-in', 'Python Built-in Module'), ('Python-tool', 'Python Coding Tool'), ('Python-external', 'Python External Module'), ('Python', 'Python Tutorial'), ('Django', 'Django Tutorial'), ('Flask', 'Flask Tutorial')], default='Python Tutorial', max_length=20),
        ),
    ]
