# Generated by Django 2.2.7 on 2020-01-08 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_auto_20200108_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Category',
            field=models.CharField(choices=[('Django', 'Django Tutorial'), ('Python-tool', 'Python Coding Tool'), ('Python-external', 'Python External Module'), ('Python', 'Python Tutorial'), ('Python-built-in', 'Python Built-in Module'), ('Flask', 'Flask Tutorial')], default='Python Tutorial', max_length=20),
        ),
        migrations.AlterField(
            model_name='logo',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='logos', verbose_name='Website Logo'),
        ),
        migrations.AlterField(
            model_name='logo',
            name='siteicon',
            field=models.FileField(blank=True, null=True, upload_to='icons', verbose_name='Website Icon'),
        ),
    ]
