# Generated by Django 2.2.7 on 2020-01-22 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_auto_20200108_0501'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageone', models.FileField(blank=True, upload_to='First', verbose_name='First Image:- ')),
                ('imagetwo', models.FileField(blank=True, upload_to='Second', verbose_name='Second Image:- ')),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='Category',
            field=models.CharField(choices=[('Python-external', 'Python External Module'), ('Flask', 'Flask Tutorial'), ('Python-built-in', 'Python Built-in Module'), ('Python-tool', 'Python Coding Tool'), ('Django', 'Django Tutorial'), ('Python', 'Python Tutorial')], default='Python Tutorial', max_length=20),
        ),
    ]
