# Generated by Django 2.2.7 on 2020-01-22 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_auto_20200122_0845'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(max_length=300, verbose_name='Site Description:- ')),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='Category',
            field=models.CharField(choices=[('Python', 'Python Tutorial'), ('Python-tool', 'Python Coding Tool'), ('Flask', 'Flask Tutorial'), ('Python-built-in', 'Python Built-in Module'), ('Python-external', 'Python External Module'), ('Django', 'Django Tutorial')], default='Python Tutorial', max_length=20),
        ),
    ]
