# Generated by Django 2.2.7 on 2020-01-22 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_auto_20200122_0944'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50, verbose_name='Footer text')),
                ('textlink', models.CharField(max_length=50, verbose_name='Footer link text')),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='Category',
            field=models.CharField(choices=[('Python', 'Python Tutorial'), ('Python-tool', 'Python Coding Tool'), ('Flask', 'Flask Tutorial'), ('Python-external', 'Python External Module'), ('Django', 'Django Tutorial'), ('Python-built-in', 'Python Built-in Module')], default='Python Tutorial', max_length=20),
        ),
    ]
