# Generated by Django 2.2.7 on 2020-02-26 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_auto_20200122_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myprofile', models.FileField(upload_to='me')),
                ('yourprofile', models.ImageField(upload_to='you')),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='Category',
            field=models.CharField(choices=[('Python', 'Python Tutorial'), ('Python-built-in', 'Python Built-in Module'), ('Django', 'Django Tutorial'), ('Python-external', 'Python External Module'), ('Python-tool', 'Python Coding Tool'), ('Flask', 'Flask Tutorial')], default='Python Tutorial', max_length=20),
        ),
    ]
