# Generated by Django 2.2.7 on 2020-02-27 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_auto_20200226_0741'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchEngineOptimization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Site Title (70 Characters)')),
                ('description', models.TextField(max_length=150, verbose_name='Site Description (150 Characters)')),
                ('keyword', models.TextField(max_length=200, verbose_name='Site Keywords (200 Characters)')),
                ('author', models.CharField(max_length=50, verbose_name='Site Author (50)')),
                ('contenttype', models.CharField(max_length=20, verbose_name='Content Type')),
                ('robotfollow', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20, verbose_name='Allow robots to follow all links?')),
                ('robotindex', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20, verbose_name='Allow robots to index your website?')),
                ('language', models.CharField(choices=[('English', 'English'), ('Hindi', 'Hindi'), ('French', 'French'), ('Spanish', 'Spanish')], max_length=20, verbose_name='What is your site primary language?')),
            ],
            options={
                'verbose_name': 'Search Engine Optimization Setting',
            },
        ),
        migrations.DeleteModel(
            name='ProfilePicture',
        ),
        migrations.AlterField(
            model_name='blog',
            name='Category',
            field=models.CharField(choices=[('Flask', 'Flask Tutorial'), ('Python-tool', 'Python Coding Tool'), ('Python-built-in', 'Python Built-in Module'), ('Python', 'Python Tutorial'), ('Python-external', 'Python External Module'), ('Django', 'Django Tutorial')], default='Python Tutorial', max_length=20),
        ),
    ]
