# Generated by Django 2.2.7 on 2020-02-27 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_auto_20200227_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Category',
            field=models.CharField(choices=[('Python', 'Python Tutorial'), ('Python-built-in', 'Python Built-in Module'), ('Flask', 'Flask Tutorial'), ('Python-external', 'Python External Module'), ('Django', 'Django Tutorial'), ('Python-tool', 'Python Coding Tool')], default='Python Tutorial', max_length=20),
        ),
        migrations.AlterField(
            model_name='searchengineoptimization',
            name='keyword',
            field=models.TextField(max_length=200, verbose_name='Site Keywords (200 Characters) (Separate with commas)'),
        ),
    ]
