# Generated by Django 2.2.7 on 2020-02-27 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_auto_20200227_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Category',
            field=models.CharField(choices=[('Python-built-in', 'Python Built-in Module'), ('Flask', 'Flask Tutorial'), ('Django', 'Django Tutorial'), ('Python-tool', 'Python Coding Tool'), ('Python-external', 'Python External Module'), ('Python', 'Python Tutorial')], default='Python Tutorial', max_length=20),
        ),
        migrations.AlterField(
            model_name='searchengineoptimization',
            name='robotfollow',
            field=models.CharField(choices=[('index,', 'Yes'), ('noindex', 'No')], max_length=20, verbose_name='Allow robots to follow all links?'),
        ),
        migrations.AlterField(
            model_name='searchengineoptimization',
            name='robotindex',
            field=models.CharField(choices=[('follow', 'Yes'), ('nofollow', 'No')], max_length=20, verbose_name='Allow robots to index your website?'),
        ),
    ]
