# Generated by Django 2.2.7 on 2020-03-02 09:07

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_auto_20200227_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=50, verbose_name='Product Name:- ')),
                ('pprice', models.IntegerField(verbose_name='Product Price:- ')),
                ('pimage', models.FileField(upload_to='Product', verbose_name='Image of Product:- ')),
                ('pspecification', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Product description')),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='Category',
            field=models.CharField(choices=[('Python-tool', 'Python Coding Tool'), ('Python-built-in', 'Python Built-in Module'), ('Django', 'Django Tutorial'), ('Python-external', 'Python External Module'), ('Flask', 'Flask Tutorial'), ('Python', 'Python Tutorial')], default='Python Tutorial', max_length=20),
        ),
    ]
