# Generated by Django 2.2.7 on 2020-03-02 09:14

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_auto_20200302_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Category',
            field=models.CharField(choices=[('Python', 'Python Tutorial'), ('Django', 'Django Tutorial'), ('Python-built-in', 'Python Built-in Module'), ('Python-tool', 'Python Coding Tool'), ('Flask', 'Flask Tutorial'), ('Python-external', 'Python External Module')], default='Python Tutorial', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='pspecification',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
