# Generated by Django 2.2.7 on 2020-03-02 09:16

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_auto_20200302_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Category',
            field=models.CharField(choices=[('Flask', 'Flask Tutorial'), ('Django', 'Django Tutorial'), ('Python', 'Python Tutorial'), ('Python-tool', 'Python Coding Tool'), ('Python-external', 'Python External Module'), ('Python-built-in', 'Python Built-in Module')], default='Python Tutorial', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='pspecification',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
