# Generated by Django 2.2.7 on 2020-03-02 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_auto_20200302_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pslug',
            field=models.SlugField(default='product'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='Category',
            field=models.CharField(choices=[('Python-external', 'Python External Module'), ('Django', 'Django Tutorial'), ('Python', 'Python Tutorial'), ('Python-built-in', 'Python Built-in Module'), ('Flask', 'Flask Tutorial'), ('Python-tool', 'Python Coding Tool')], default='Python Tutorial', max_length=20),
        ),
    ]
